STATIONS = 'stations'
PLATFORMS = 'platforms'
ROUTES = 'routes'
DIRECTIONS = 'directions'
STATION_PLATFORMS = 'station_platforms'
STATION_ROUTES = 'station_routes'
ROUTE_DIRECTIONS = 'route_directions'
DIRECTION_PLATFORMS = 'direction_platforms'
EXCLUDE_ROUTES = 'exclude_routes'
BREAK_POINTS = 'breakpoints'
DIRECTION_LINKS = 'direction_links'

TABLES = [STATIONS, PLATFORMS, ROUTES, DIRECTIONS, STATIONS, DIRECTIONS, EXCLUDE_ROUTES, BREAK_POINTS, DIRECTION_LINKS]
CONNECTIONS = [STATION_PLATFORMS, STATION_ROUTES, ROUTE_DIRECTIONS, DIRECTION_PLATFORMS]
