
# START 700

# /v2/login
SINGLE_CREDENTIAL_REQUIRED = 700
USERNAME_EMAIL_OR_PHONE_REQUIRED = 701
PASSWORD_INCORRECT = 703
SOCIALS_TOKEN_NOT_VERIFIED = 704
NO_VALID_CREDENTIALS_PROVIDED = 705  # means: no valid(!) (username and pwd) or (type and token)
NO_USER_REGISTERED_WITH_GIVEN_CREDENTIALS = 706
LOGIN_PARAMETER_REQUIRED = 707
TOKEN_PARAMETER_REQUIRED = 708
TYPE_PARAMETER_REQUIRED = 709


# /v2/register
EMAIL_OR_PHONE_MUST_PRESENT = 720

CREDENTIALS_NOT_PROVIDED = 721

USERNAME_ALREADY_EXISTS = 722

SOCIAL_USER_ALREADY_REGISTERED = 723

# aka phone or email already registered
USER_ALREADY_EXISTS = 724

# phone or email not verified
NO_VERIFIED_CONTACT_PROVIDED = 725

# frontend should never see those codes
TRANSPORT_ORGANIZATION_REQUIRED_TO_SET_USER_AS_TRANSPORT_DRIVER = 726
TRANSPORT_NOT_FOUND = 727
TRANSPORT_ORGANIZATION_NOT_FOUND = 728

# user requirements
EMAIL_IS_NOT_VALID = 729
NAME_IS_NOT_VALID = 730
AGE_IS_NOT_VALID = 731
PAYLOAD_IS_NOT_VALID = 732
USERNAME_IS_NOT_VALID = 733
# NOT same as PASSWORD_INCORRENT, just validity
PASSWORD_IS_NOT_VALID = 734
NATIONAL_CODE_IS_NOT_VALID = 735

LOGIN_ALREADY_BOUND_TO_USER = 736


# /v1/verify*
PHONE_IS_NOT_VALID = 740
REQUEST_VERIFICATION_EXPIRED_OR_NOT_EXISTS = 741
REQUEST_VERIFICATION_FOR_PHONE_FIRST = 741
PHONE_VERIFICATION_ERROR = 742
SMTP_VERIFICATION_ERROR = 753

REQUEST_VERIFICATION_FOR_EMAIL_FIRST = 743
VALUE_MUST_BE_VALID_EMAIL_OR_PHONE = 744
INVALID_CODE = 745
TOO_MANY_SEND_ATTEMPTS = 746
TOO_MANY_CHECK_ATTEMPTS = 747
SHAHKAR_VERIFY_FAILED = 748
LOGIN_VERIFY_FAILED = 749
GENDER_IS_NOT_VALID = 751
MAC_IS_NOT_PROVIDED = 752

# /v2/register
NATIONAL_CODE_NOT_PROVIDED = 750


# /v1/login/check
ONLY_EMAIL_OR_PHONE_MUST_PRESENT = 760

# /v1/restore_access
NO_USER_REGISTERED_WITH_GIVEN_CONTACT = 780
NO_PASSWORD_PARAMETER_PRESENTS_OR_IS_NOT_VALID = 781
EMAL_FOR_IRAN_RESTRICTED = 782
